name: CI

on:
  push:
    branches: [package]
  pull_request:
    branches: [package]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: package
      - name: Setup Python
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Setup Java JDK        
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8
      - name: Installation
        run: pip install . ; pip install pytest pylint pytest-cov ; mkdir -p ./coverage/reports/
      - name: Unit Testing
        env:
          MTI_USERNAME: ${{ secrets.MTI_USERNAME }}
          MTI_PASSWORD: ${{ secrets.MTI_PASSWORD }}
        run: export PYTHONPATH="." ; pytest --cov=reactome_query_utils --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          directory: ./coverage/reports/
          flags: unittests
          name: utils-ci
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
      - name: Quality Check
        run: python3 run_pylint.py --disable=line-too-long,invalid-name,too-many-arguments,too-many-locals,too-few-public-methods,broad-except,too-many-instance-attributes,too-many-function-args --fail-under=9 reactome_query_utils
